booksystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.urls import path, include
from mainapp import views

app_name = "mainapp"
urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.login, name='login'),
	path('log_out/', views.log_out, name='log_out'),
	path('passwordforgotten/', views.passwordforgotten, name='passwordforgotten'),
	path('update_profile/', views.update_profile, name='update_profile'),
	path('user_shelf/', views.user_shelf, name='user_shelf'),
	path('book_page/<slug:isbn_13>/', views.book_page, name='book_page'),
	path('not_found/', views.not_found, name='not_found'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('permissiondenied/', views.permissiondenied, name='permissiondenied'),
	path('add_user_country_browser/', views.add_user_country_browser, name='add_user_country_browser'),
	path('dashboard/add_user_country_browser/', views.dashboard_live_data, name='dashboard_live_data')
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
import jsonfield
# Create your models here.

class CustomerAccountProfile(models.Model):
	userid = models.ForeignKey(User, on_delete=models.CASCADE)
	birthDate = models.DateField()
	gender = models.CharField(max_length=1000)
	userfavouritegenre =  models.CharField(max_length=1000)

class Book(models.Model):
	isbn_13 = models.CharField(max_length=15)
	isbn_10 = models.CharField(max_length=15)
	title =  models.CharField(max_length=1000, default=None)
	book_data = jsonfield.JSONField()
	favourites = models.ManyToManyField(CustomerAccountProfile, related_name='favourites', default="none")
	readingnow = models.ManyToManyField(CustomerAccountProfile, related_name='readingnow', default="none")
	toread = models.ManyToManyField(CustomerAccountProfile, related_name='toread', default="none")
	haveread = models.ManyToManyField(CustomerAccountProfile, related_name='haveread' ,default="none")

class Review(models.Model):
	bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
	customerID = models.ForeignKey(CustomerAccountProfile, on_delete=models.CASCADE)
	description = models.TextField(max_length=1000)
	rating_value = models.IntegerField(default=0)
	created_at = models.DateTimeField()
	likes = models.ManyToManyField(CustomerAccountProfile, related_name='likes', default="none")
	dislikes = models.ManyToManyField(CustomerAccountProfile, related_name='dislikes', default="none")

class Category(models.Model):
	name = models.CharField(max_length=1000)

class Metrics(models.Model):
	metrics_data = jsonfield.JSONField()

mainapp/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponse, QueryDict, JsonResponse#, HttpResponseRedirect, Http404
# from django.template import RequestContext, loader
from django.contrib.sessions.models import Session
# from django.contrib.auth.hashers import make_password
# from django.db import IntegrityError
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import logout, authenticate, login as auth_login
# from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import CustomerAccountProfile, Book, Review, Category, Metrics
import string, random, csv, re, os, unidecode, time, requests, ssl, smtplib, uuid
# from django.contrib.auth.forms import PasswordChangeForm
from datetime import datetime as dt
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel
# from scipy import sparse
# from sklearn.metrics.pairwise import cosine_similarity
from datetime import date
from django.core.mail import send_mail
# Create your views here.

@csrf_exempt
def index(request):
	start_time = time.time()
	metric = Metrics.objects.all()[0].metrics_data

	if request.method == "POST":
		metric["post_request_count"]+=1
		Metrics.objects.filter(id=1).update(metrics_data=metric)
		
		booksearch = request.POST['booksearch']
		response = requests.get("https://www.googleapis.com/books/v1/volumes?q="+booksearch)
		requested_books = []
		try:
			json_response = response.json()["items"]
			for book in json_response:
				try:
					if(len(book['volumeInfo']['industryIdentifiers'])==2):
						uid = book['id']
						etag = book['etag']
						title = book['volumeInfo']['title']

						if('authors' in  book['volumeInfo']):
							authors = book['volumeInfo']['authors']
							authors.sort()
							authors = ",".join(authors)
						else:
							authors = "None"

						if('publisher' in book['volumeInfo']):
							publisher = book['volumeInfo']['publisher']
						else:
							publisher = "None"

						if('publishedDate' in book['volumeInfo']):
							publishedDate = book['volumeInfo']['publishedDate']
						else:
							publishedDate = "None"

						if('description' in book['volumeInfo']):
							description = book['volumeInfo']['description']
						else:
							description = "None"

						ISBN_13 = None
						ISBN_10 = None
						if(book['volumeInfo']['industryIdentifiers'][0]['type'] == "ISBN_10"):
							ISBN_10 = book['volumeInfo']['industryIdentifiers'][0]['identifier']
						elif(book['volumeInfo']['industryIdentifiers'][0]['type'] == "ISBN_13"):
							ISBN_13 = book['volumeInfo']['industryIdentifiers'][0]['identifier']

						if(book['volumeInfo']['industryIdentifiers'][1]['type'] == "ISBN_10"):
							ISBN_10 = book['volumeInfo']['industryIdentifiers'][1]['identifier']
						elif(book['volumeInfo']['industryIdentifiers'][1]['type'] == "ISBN_13"):
							ISBN_13 = book['volumeInfo']['industryIdentifiers'][1]['identifier']

						if('categories' in book['volumeInfo']):
							categorie = book['volumeInfo']['categories']
							categories = [i.title().replace(",", " &").replace("  ", "") for i in categorie]
						else:
							categories = ["None"]

						if('averageRating' in book['volumeInfo']):
							averageRating = book['volumeInfo']['averageRating']
						else:
							averageRating = 0.0
						averageRating = round(averageRating,1)

						if('ratingsCount' in book['volumeInfo']):
							ratingsCount = book['volumeInfo']['ratingsCount']
						else:
							ratingsCount = 0

						try:
							if('thumbnail' in book['volumeInfo']['imageLinks']):
								thumbnail = book['volumeInfo']['imageLinks']['thumbnail']
						except:
							thumbnail = "None"

						checkBookExist = Book.objects.filter(isbn_13=ISBN_13)
						if(len(checkBookExist)==0):
							print("New book")
							book_data = {"id": uid, "etag": etag, "title": title,
							"authors": authors, "publisher": publisher, "publishedDate": publishedDate,
							"description": description, "ISBN_10": ISBN_10, "ISBN_13": ISBN_13,
							"categories": categories, "averageRating": averageRating, "ratingsCount": ratingsCount,
							"thumbnail": thumbnail}

							book_genre = " ".join(categories)
							book_genre = book_genre.replace("&", "").replace("  ", " ")

							# Adding the genre/category to DB.
							category_db = "".join(categories)
							category_db = category_db.split("&")

							for item in category_db:
								if(item!="None"):
									split_item = list(item)
									if(split_item[0]==" "):
										split_item = split_item[1:]
									if(split_item[len(split_item)-1]==" "):
										split_item = split_item[:len(split_item)-1]
									item = "".join(split_item)
									item = item.replace(",", " ").replace("-", " ").replace("  ", " ")
									item = ''.join(e for e in item if e.isalnum() or e==" ")
									item = re.sub(" +", " ", item)
									item = unidecode.unidecode(item)
									checkGenreExist = Category.objects.filter(name=item)
									if(len(checkGenreExist)==0):
										Category.objects.create(name=item)

							with open('book_rating.csv', 'a') as br_writer, open('book_info.csv', 'a') as bi_writer, open('book_description.csv', 'a') as bd_writer:
								# Fields are isbn_13,book_genre,favourites_count,reading_now_count,to_read_count,have_read_count,average_rating,rating_count
								br_write = "\n"+ISBN_13+","+book_genre+","+"0"+","+"0"+","+"0"+","+"0"+","+str(2*averageRating)+","+str(ratingsCount)
								
								# Fields are isbn_13,title,authors,publisher,publishedDate
								authors = authors.replace(",", " ").replace("-", " ").replace("–", " ")
								authors = ''.join(e for e in authors if e.isalnum() or e==" ")
								authors = re.sub(" +", " ", authors)
								authors = unidecode.unidecode(authors)

								publisher = publisher.replace(",", " ").replace("-", " ").replace("–", " ")
								publisher = ''.join(e for e in publisher if e.isalnum() or e==" ")
								publisher = re.sub(" +", " ", publisher)
								publisher = unidecode.unidecode(publisher)

								title = title.replace(",", " ").replace("-", " ").replace("–", " ")
								title = ''.join(e for e in title if e.isalnum() or e==" ")
								title = re.sub(" +", " ", title)
								title = unidecode.unidecode(title)
								#Use regular expression to allow letters numbers and brackets
								bi_write = "\n"+ISBN_13+","+title+","+authors+","+publisher.title()+","+publishedDate.replace("-","/")

								description = description.replace(",", " ").replace("-", " ").replace("–", " ")
								description = ''.join(e for e in description if e.isalnum() or e==" ")
								description = re.sub(" +", " ", description)
								description = unidecode.unidecode(description)
								bd_write = "\n"+ISBN_13+","+description

								br_writer.write(br_write)
								bi_writer.write(bi_write)
								bd_writer.write(bd_write)

								# Only create books when successfully written to csv
								Book.objects.create(isbn_13=ISBN_13, isbn_10=ISBN_10, title=title, book_data=book_data)
								print("Create New Book")
						requested_books.append(ISBN_13)
				except:
					pass
		except:
			pass
		required_book_objects = []
		for isbn_13 in requested_books:
			book_object = Book.objects.get(isbn_13=isbn_13)
			the_data = book_object.book_data
			required_book_objects.append({"uid":the_data["id"], "averageRating":the_data["averageRating"], "ratingsCount":the_data["ratingsCount"], "authors":the_data["authors"],"isbn_13": the_data["ISBN_13"], "isbn_10": the_data["ISBN_10"], "title": the_data["title"], "thumbnail": the_data["thumbnail"]})
		return render(request,"mainapp/frontpage.html", {"bookresults":required_book_objects,"booksearch":booksearch})
	#Can use this for displaying this items in book.html with tag: Book's with good ratings.
	try:
		average_rating_recommendation = weighted_average_and_favourite_score(request)
	except:
		average_rating_recommendation = []

	# Getting the recently added items
	all_books = Book.objects.all()
	top_20_books = all_books[len(all_books)-20:] if all_books.count()>20 else all_books[:]
	recently_added_books = []

	for items in top_20_books:
		the_data = items.book_data
		book_item = {"isbn_13": items.isbn_13, "isbn_10": items.isbn_10, "title": items.title, "thumbnail": the_data["thumbnail"]}
		recently_added_books.append(book_item)

	other_user_favourite_books = []
	if request.user.is_authenticated and not request.user.is_superuser:
		other_user_favourite_books = content_based_similar_user_items(request)

	# Metric update
	metric["total_page_visit"] +=1
	metric["get_request_count"] +=1
	metric["page_visit_counter"]["frontpage"]+=1

	duration = time.time() - start_time
	duration = int(duration * 1000)
	all_times = metric["page_load"]["frontpage"]
	all_times.append(duration)
	if(len(all_times)>50):
		all_times = all_times[-50:]
	metric["page_load"]["frontpage"] = all_times
	Metrics.objects.filter(id=1).update(metrics_data=metric)
	return render(request,'mainapp/frontpage.html',{"recently_added_books": recently_added_books,"average_rating_recommendation": average_rating_recommendation, "other_user_favourite_books": other_user_favourite_books,"carousel":True})

@csrf_exempt
def signup(request):
	start_time = time.time()
	metric = Metrics.objects.all()[0].metrics_data
	if request.method == 'POST':
		metric["post_request_count"] +=1
		Metrics.objects.filter(id=1).update(metrics_data=metric)
		fullname = request.POST['fullname']
		email = request.POST['email']
		password = request.POST['password']

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Fonts -->
	    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
	    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
	    <link rel="icon" href="Favicon.png">

	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
	    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

		<title>LibrarySystem</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}"/>

		<!-- Sweet Alert Box -->
		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

		<!-- Carousel Library -->
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
		<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

	</head>
	<style type="text/css">
		/*.nav>li{
			display: inline-block;
		}*/
	</style>
	<body>
		
	    <!--Start of Navigation bar-->
	    <nav class="navbar navbar-inverse" style="background-color: #002952"><!--navbar-default for white navbar-->
	    	<div class="container-fluid">
	    		<div class="navbar-header">
	    			<a class="navbar-brand" href="{% url 'mainapp:index' %}" >BookWire</a>
	    		</div>
	    		<ul class="nav navbar-nav navbar-right" style="background-color: #002952">
	    			<li class="active"><a href="{% url 'mainapp:index' %}" style="background-color: #002952">Home</a></li>
	    			{% if user.is_authenticated %}
	    				{% if user.is_superuser %}
	    					<li class="dropdown">
	    						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Account<span class="caret"></span></a>
	    						<ul class="dropdown-menu">
	    							<li style="display: inline-block;"><a href="{% url 'mainapp:log_out' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
	    							<li style="display: inline-block;"><a href="{% url 'mainapp:dashboard' %}"><span class="glyphicon glyphicon-blackboard"></span> Dashboard</a></li>
	    						</ul>
	    					</li>
	    				{% else %}
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">Account<span class="caret"></span></a>
									<ul class="dropdown-menu">
									<li style="display: inline-block;"><a href="{% url 'mainapp:log_out' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
									<li style="display: inline-block;"><a href="{% url 'mainapp:update_profile' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
									<li style="display: inline-block;"><a href="{% url 'mainapp:user_shelf' %}"><span class="glyphicon glyphicon-book"></span> My Shelf</a></li>
								</ul>
							</li>
	    				{% endif %}
	    			{% else %}
	    			<li class="dropdown">
	    				<a class="dropdown-toggle" data-toggle="dropdown" href="#" style="background-color: #002952">Login/Sign Up<span class="caret"></span></a>
	    				<ul class="dropdown-menu">
	    					<li style="display: inline-block;"><a href="{% url 'mainapp:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          					<li style="display: inline-block;"><a href="{% url 'mainapp:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        				</ul>
	    			</li>
	    			{% endif %}
    			</ul>
  			</div>
		</nav>
		{% block content %}
        {% endblock %}
        <section class="copyright">
			<!-- <div class="container"> -->
				<div class="row">
					<div class="col-md-12 ">
						<div class="text-center text-white" style="position: fixed; left: 0; bottom: 0; width: 100%; background-color: #002952; color: white; text-align: center;">
							&copy; 2019-2020 BookWire. All Rights Reserved.
						</div>
					</div>
				</div>
			<!-- </div> -->
		</section>
		<!-- End of Navigation bar -->

		<!-- Start of Banner & Search -->

		<!-- End of Banner & Search -->
	<!-- <script src="//instant.page/3.0.0" type="module" defer integrity="sha384-OeDn4XE77tdHo8pGtE1apMPmAipjoxUQ++eeJa6EtJCfHlvijigWiJpD7VDPWXV1"></script> for faster page load -->

	</body>
</html>

mainapp/templates/mainapp/forgotpassword.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
	.div-inline {
      display:inline-block;
    }
</style>
<div class="container">
    <form id="paswordform" class="form-horizontal" role="form" method="post" action="{% url 'mainapp:passwordforgotten' %}"><!--action="{% url 'mainapp:signup' %}"-->
        {% csrf_token %}
        <h1>Forgotten your Password?</h1><br><br>
        <h4>Please fill your details below!</h4>
        <div class="form-group">
            <label for="email" class="col-sm-3 control-label">Email</label>
            <div class="col-sm-9">
                <input type="email" id="email" name="email" placeholder="Email" class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="fullname" class="col-sm-3 control-label">Full Name</label>
            <div class="col-sm-9">
                <input type="text" id="fullname" name="fullname" placeholder="Full Name" class="form-control" maxlength="30" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="birthDate" class="col-sm-3 control-label">Date of Birth</label>
            <div class="col-sm-9">
                <input type="date" id="birthDate" name="birthDate"  class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <button type="submit" class="btn btn-primary btn-block">Request</button>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    /* Code to prevent users from choosing future data-of-birth*/
    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth()+1; //January is 0!
    var yyyy = today.getFullYear();

    if(dd<10){
        dd='0'+dd
    }
    if(mm<10){
        mm='0'+mm
    }
    today = yyyy+'-'+mm+'-'+dd;
    document.getElementById("birthDate").setAttribute("max", today);
    function postToRequest(){
        var email = document.getElementById("email").value;
        var fullname = document.getElementById("fullname").value;
        var birthDate = document.getElementById("birthDate").value;

        // $.ajax({
        //     type: "POST",
        //     data:{
        //         email: email,
        //         fullname: fullname,
        //         birthDate: birthDate,
        //         csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
        //     }
        // })
    }
	// function postToRequest(){
	// 	var emailvalue = document.getElementById("requestemailvalue").value;
	// 	console.log(emailvalue);
	// 	$.ajax({
	// 		type: "POST",
	// 		data: {
 //                email: emailvalue,
 //                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
 //            },
 //            success: function(message){
 //                alert(message);
 //            	if(!document.getElementById("confirmationidvalue")){
 //                    $("#paswordform").append('<br><div class="input-group"><input id="confirmationidvalue" placeholder="Enter your confirmation id here here" class="form-control width100" required><span class="input-group-btn" required><button class="btn btn-primary" onclick="checkconfirmationid();return false;">Submit</button></span></div>');
 //            	}
 //            }
	// 	})
	// }

	// var checkconfirmationid =  function(){
	// 	var idvalue = document.getElementById("confirmationidvalue").value;
 //        $.ajax({
 //            type: "POST",
 //            data: {
 //                idvalue: idvalue,
 //                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
 //            },
 //            success: function(message){
 //                if(message=="codevalid"){
 //                    $("#paswordform").append('<br><div class="input-group"><input id="newpassword" placeholder="Enter your new password here" class="form-control width100" required><span class="input-group-btn" required><button class="btn btn-primary" onclick="sendpasword();return false;">Submit</button></span></div>');
 //                }
 //                else{
 //                    alert("You code is invalid, please try again!")
 //                }
 //            }
 //        })
	// }
 //    console.log("AA");
</script>
{% endblock %}

mainapp/templates/mainapp/login.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
}
.center_div{
    margin: 0 auto;
    width:80% /* value of your choice which suits your alignment */
}
</style>
<div class="container">
    <form class="form-horizontal" role="form" method="post"><!--action="{% url 'mainapp:signup' %}"-->
        {% csrf_token %}
        <h2>Login</h2>
        <div class="form-group">
            <label for="email_address" class="col-sm-3 control-label">E-Mail Address</label>
            <div class="col-sm-9">
                <input type="text" id="email" class="form-control" placeholder="E-Mail" required autofocus>
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-sm-3 control-label">Password</label>
            <div class="col-sm-9">
                <input type="password" id="password" placeholder="Password" minlength="8" class="form-control" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9">
                <button type="submit" class="btn btn-primary" onclick="postTologin();return false;">Login</button>
                <a href="{% url 'mainapp:passwordforgotten' %}" class="btn btn-link">Forgot Your Password?</a>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    function postTologin(){
        var email = document.getElementById("email").value;
        var password = document.getElementById("password").value;
        console.log(email);
        console.log(password);
        $.ajax({
            type: "POST",
            data: {
                email: email,
                password: password,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(info){
                if(info=="Sorry! Username and Password didn't match, Please try again!"){
                    Swal.fire({ icon: 'error', title: 'Oops...', text: "Sorry! Username and Password didn't match, Please try again!"})
                    // alert("Sorry! Username and Password didn't match, Please try again!")
                }
                else{
                    window.location = "{% url 'mainapp:index' %}";
                    // history.back(-2);
                }
                // Code for returing to privous page after successfull login
                // else{
                //     var previous_URL = document.referrer;                    
                //     previous_URL = previous_URL.split("/");

                //     if(previous_URL[3]=="signup" || previous_URL[3]=="login"){
                //         var authority = previous_URL.slice(0, 3);
                //         authority[1]="//";
                //         authority = authority.join("");
                //         //var url = "{% url 'mainapp:index' %}"
                //         var final_URL = authority+"/"
                //         window.location = final_URL;
                //         return;
                //     } else {
                //         var authority = previous_URL.slice(0, 3);
                //         authority[1]="//";
                //         authority = authority.join("");
                //         var fragment = previous_URL.slice(3);
                //         fragment = fragment.join("/");
                //         var final_URL = authority+"/"+fragment
                //         window.location = final_URL;
                //     }
                // }
            }
        })
    }
</script>
{% endblock %}

mainapp/templates/mainapp/permissiondenied.html
{% load static %}
<!-- https://codepen.io/saransh/pen/aezht -->
<link rel="stylesheet" type="text/css" href="{% static 'css/404.css' %}"/>
{% block content %}
<div class="container">
    <svg width="380px" height="500px" viewBox="0 0 837 1045" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
            <path d="M353,9 L626.664028,170 L626.664028,487 L353,642 L79.3359724,487 L79.3359724,170 L353,9 Z" id="Polygon-1" stroke="#007FB2" stroke-width="6" sketch:type="MSShapeGroup"></path>
            <path d="M78.5,529 L147,569.186414 L147,648.311216 L78.5,687 L10,648.311216 L10,569.186414 L78.5,529 Z" id="Polygon-2" stroke="#EF4A5B" stroke-width="6" sketch:type="MSShapeGroup"></path>
            <path d="M773,186 L827,217.538705 L827,279.636651 L773,310 L719,279.636651 L719,217.538705 L773,186 Z" id="Polygon-3" stroke="#795D9C" stroke-width="6" sketch:type="MSShapeGroup"></path>
            <path d="M639,529 L773,607.846761 L773,763.091627 L639,839 L505,763.091627 L505,607.846761 L639,529 Z" id="Polygon-4" stroke="#F2773F" stroke-width="6" sketch:type="MSShapeGroup"></path>
            <path d="M281,801 L383,861.025276 L383,979.21169 L281,1037 L179,979.21169 L179,861.025276 L281,801 Z" id="Polygon-5" stroke="#36B455" stroke-width="6" sketch:type="MSShapeGroup"></path>
        </g>
    </svg>
    <div class="message-box">
        <h1>403</h1>
        <p>Sorry, your access is refused due to security reasons of our server and also our sensitive data.<br/>Please go back to the previous page to continue browsing.</p>
        <div class="buttons-con">
            <div class="action-link-wrap">
                <a onclick="history.back(-1)" class="link-button link-back-button">Go Back</a>
                <a href="{% url 'mainapp:index' %}" class="link-button">Go to Home Page</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/resetpasswordconfirm.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<div class="container">
	<h3>We've emailed you instructions for setting your password, if an account exists with the email and details you entered. You should receive them shortly.</h3>
	<h3>If you don't receive an email, please make sure you've entered the address you registered with, check other entered details and check your spam folder.</h3>
	<a href="{% url 'mainapp:login' %}" class="link-button">Go to Login Page</a>
</div>
{% endblock %}